### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by fadenb**
Pretty much the same code as used for IPv4.

### CODE REVIEW

**Comment by tripledes** [comment]
Hi!

thanks for the PR! I noticed the _FIXME_ comment to make sure an IPv6 is not accepted as value for _ipv4_ parameter, what do you think about using [ipaddr#ipv6?](http://ruby-doc.org/stdlib-1.9.3/libdoc/ipaddr/rdoc/IPAddr.html#method-i-ipv6-3F) and [ipaddr#ipv4?](http://ruby-doc.org/stdlib-1.9.3/libdoc/ipaddr/rdoc/IPAddr.html#method-i-ipv4-3F), thus removing the dirty validation done currently calling _ipaddr#new_?

Cheers!

**Comment by fadenb** [comment]
Will do that sometime today and update the PR :)

**Comment by tripledes** [comment]
awesome, thanks!

**Comment by fadenb** [comment]
Is this how you imagined the check to be implemented?
If there is anything else to do just let me know :)

**Comment by tripledes** [comment]
Awesome, thanks!

**Pull request merged**
